server:
  port: 89
spring:
  datasource:
    url: jdbc:mysql://sql6.freesqldatabase.com/sql6583826
    username: { DB_USER_NAME }
    password: { DB_PASSWORD }
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

