server:
  port: 89
spring:
  datasource:
    url: jdbc:mysql://sql6.freesqldatabase.com/sql6583826
    username: sql6583826
    password: RNeyeKBde9
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

